# Generated by Django 5.1.7 on 2025-03-24 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aynage_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='updated_at',
            new_name='updated_att',
        ),
    ]
