# Generated by Django 5.1.7 on 2025-03-24 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aynage_app', '0002_rename_updated_at_blog_updated_att'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='updated_att',
            new_name='updated_at',
        ),
    ]
