# Generated by Django 5.1.7 on 2025-03-25 14:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aynage_app', '0004_delete_category_rename_date_added_vacancy_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
