# Generated by Django 5.1.7 on 2025-03-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aynage_app', '0005_alter_blog_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('tech', 'Technology'), ('fashion', 'Fashion'), ('help', 'Help'), ('ngo', 'NGO')], max_length=100)),
                ('img', models.ImageField(upload_to='gallery/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='banner',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.IntegerField(choices=[(1, 'Published'), (0, 'Unpublished')]),
        ),
    ]
