# Generated by Django 5.1.7 on 2025-03-31 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aynage_app', '0010_vacancy_position_alter_blog_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='position',
        ),
    ]
