# Generated by Django 5.1.7 on 2025-04-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aynage_app', '0011_remove_vacancy_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
