# Generated by Django 5.1.7 on 2025-04-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aynage_app', '0012_vacancy_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
