# Generated by Django 5.1.7 on 2025-04-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aynage_app', '0013_vacancy_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
