# Generated by Django 5.2.13 on 2026-05-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gachana_app', '0016_staffdesignation_user_role_donation_memberprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_giving_goal', models.DecimalField(decimal_places=2, default=100000, help_text='Community fundraising target shown to all members (ETB).', max_digits=12)),
                ('giving_goal_headline', models.CharField(default='Help us however you can', max_length=200)),
                ('giving_goal_message', models.TextField(blank=True, default='Our annual giving goal supports programs across the community. Every gift counts—give what feels right for you.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portal settings',
                'verbose_name_plural': 'Portal settings',
            },
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='membership_goal',
            field=models.DecimalField(decimal_places=2, default=10000, help_text='Deprecated: use PortalSettings.annual_giving_goal.', max_digits=12),
        ),
    ]
