# Generated by Django 5.2.13 on 2026-05-24 15:49

import django.db.models.deletion
from django.db import migrations, models


def seed_banks(apps, schema_editor):
    DonationBank = apps.get_model('gachana_app', 'DonationBank')
    if DonationBank.objects.exists():
        return
    DonationBank.objects.bulk_create(
        [
            DonationBank(
                name='Commercial Bank of Ethiopia',
                account_name='Gachana Charity Association',
                account_number='1000123456789',
                branch='Dire Dawa',
                sort_order=1,
            ),
            DonationBank(
                name='Awash Bank',
                account_name='Gachana Charity Association',
                account_number='0130012345678',
                branch='Dire Dawa Main',
                sort_order=2,
            ),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('gachana_app', '0017_portal_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Bank name shown in the dropdown.', max_length=120)),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=80)),
                ('branch', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'donation bank',
                'verbose_name_plural': 'donation banks',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='gachana_app.donationbank'),
        ),
        migrations.RunPython(seed_banks, migrations.RunPython.noop),
    ]
